#!/bin/bash
# Unmount mounted devices via dmenu

#### DO NOT TOUCH
for i in $(mount | grep usb | cut -d " " -f 1); do
    devices="${devices}${i}\n"
done

device=$(printf "${devices}" | dmenu -p Umount)

if [ -n "$device" ]; then
    doas umount $device
fi
