#!/bin/sh
# This script will show date/time, mute/unmute, volume percent (alsa only)
# and lock keys status (except for Scroll Lock because I don't have it).

while :
value=$(xset q |grep "LED" |cut -c66)
case $value in
	0)
	key="" ;;
	1)
	key="[C]" ;;
	2)
	key="[N]" ;;
	3)
	key="[C+N]" ;;
esac

date=$(date +"%a %d %b - %H:%M")

mute=$(amixer get Master |tail -n1 |awk '{ print $6 }' | tr -d [])
case $mute in
	on)
	lvl=""
	;;
	off)
	lvl="[M]"
	;;
esac

vol=$(amixer get Master | tail -n1 | awk '{ print $4 }' | tr -d [])

do
	xsetroot -name "$date - $lvl$vol $key"
	sleep 0.1
done
