#!/bin/sh
# Add:
# <username> ALL=NOPASSWD: /sbin/poweroff, /sbin/reboot
# to /etc/sudoers
color='-i -nf darkred -nb black -sf black -sb darkred'
prompt='-p ?'
opt=$(printf "Logout\nReboot\nLock\nShutdown" | dmenu $prompt $color)
case $opt in
	'Logout') 
		sudo pkill -KILL -u $(whoami) ;;
	'Reboot') 
		sudo reboot ;;
	'Lock') 
		slock ;;
	'Shutdown') 
		sudo poweroff ;;
esac
