#!/bin/sh

fmt='-b -i -nf red -nb black -sf black -sb red -fn monospace:size=13'
menu=$(printf "#\nLock\nReboot\nShutdown" | dmenu $fmt)

 case $menu in
  #) : ;;
  Lock) slock ;;
  Reboot) doas reboot ;;
  Shutdown) doas poweroff ;;
 esac
