#!/bin/sh

options='-i -nf #600000 -nb black -sf black -sb #600000'
case $1 in
	'root')
	prompt='-p ROOT'
	opt=$(printf "Pcmanfm\nTerminal\nLeafpad\nGparted" | dmenu $prompt $options) 
;; 

	'exit')
	prompt='-p ?'
	opt=$(printf "Reiniciar\nApagar\nSalir\nBloquear" | dmenu $prompt $options) ;;

esac
		case $opt in
			'Pcmanfm') 
				sudo -A pcmanfm / ;;
			'Terminal') 
				sudo -A st ;;
			'Leafpad') 
				sudo -A leafpad ;;
			'Gparted') 
				sudo -A gparted ;;
			'Reiniciar') 
				sudo reboot ;;
			'Apagar') 
				sudo poweroff ;;
			'Salir') 
				pkill x ;;
			'Bloquear') 
				slock ;;
		esac
