#!/bin/sh
# Let's block annoying ads via Steven Black's hosts file! (must be root)

if [[ $(id -u) != 0 ]]; then
   printf 'Must be superuser! Exit.\n'
   exit 1
else
   cd /etc
   wget -N 'http://sbc.io/hosts/hosts'
fi
