#!/bin/bash
# Invokes playing script & open a loop to notify song name whenever it changes.

playing &

while true ; do
 mpc idle >/dev/null
 [[ $(mpc cur)  ]] && herbe "$(mpc cur)" & pkill -SIGUSR1 herbe
 [[ ! $(mpc cur)  ]] && :
done
